FROM node:20-alpine as build-stage

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG VITE_AUTH_API_URL
ARG VITE_PRODUCTS_API_URL
ARG VITE_INVENTORY_API_URL
ARG VITE_APP_NAME

ENV VITE_AUTH_API_URL=$VITE_AUTH_API_URL
ENV VITE_PRODUCTS_API_URL=$VITE_PRODUCTS_API_URL
ENV VITE_INVENTORY_API_URL=$VITE_INVENTORY_API_URL
ENV VITE_APP_NAME=$VITE_APP_NAME

RUN npm run build

FROM nginx:alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]